### ISSUE TITLE
Merry Christmas

### ISSUE THREAD

**Issue by MBarni458** [Kikinter/Homework_programming_3#1]
You should consider adding default events, such as Christmas.

**Comment by Kikinter** [comment]
Christmas already added, it's just not visible yet.

**Comment by MBarni458** [comment]
Thanks for the update. But please complete this feature by the 24th of December.

**Comment by Kikinter** [comment]
Feature added. Only the current year's Christmas is visible every time you open the app, to save resources. Now it's visible in the popup window if you press the button of dec 25th.
